fix: fixing a critical co-request vulnerability
emartech/suite-js-sdk pull request #171
Opened 2021-12-01 08:51 UTC by eakraml

Replaced co-request with axios. Additionally made updates on dev dependencies that contained additional vulnerabilities. The remaining vulnerabilities on semantic-release could not be updated.

Relates [SUITEDEV-29314](https://emarsys.jira.com/browse/SUITEDEV-29314)

2021-12-15 08:58 UTC, benjamingehl approved these changes

2021-12-15 13:43 UTC, Barna001 requested changes

2021-12-15 13:43 UTC, Barna001 commented on translations/collect.js
> +    const data = (response && response.data) ? JSON.parse(response.data) : {};
It wont't work, pls check out our merge request:
https://github.com/emartech/suite-js-sdk/pull/172
axios.get is smarter and returns JSON object, parsing will fail on line 44 with error msg:
SyntaxError: Unexpected token o in JSON at position 1

2021-12-16 05:07 UTC, eakraml commented on translations/collect.js
> +    const data = (response && response.data) ? JSON.parse(response.data) : {};
Cool! Thanks for finding this bug and for the hint where you already resolved it. 🙇‍♂️

2021-12-16 05:19 UTC, eakraml commented on translations/collect.js
> +    const data = (response && response.data) ? JSON.parse(response.data) : {};
@Barna001 I adapted the code as you suggested and additionally renamed the const as "translation" is much better to understand and read than "data".

2021-12-16 08:13 UTC, Barna001 approved these changes

2021-12-16 08:14 UTC, benjamingehl approved these changes

2021-12-16 08:22 UTC, merged

2021-12-16 13:18 UTC, emarsys-deployer commented
:tada: This PR is included in version 18.0.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/suite-js-sdk/v/18.0.5)
- [GitHub release](https://github.com/emartech/suite-js-sdk/releases/tag/v18.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: